# .github/workflows/ci-cd.yml
name: CI - Build and Push Docker Image

on:
  push:
    branches: [ main ] 
# main 브랜치에 푸시될 때 실행

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3 
# 다른 아키텍처 빌드 지원 (선택 사항)

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }} 

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: . # Dockerfile이 있는 경로 (프로젝트 루트)
          file: ./Dockerfile # Dockerfile 경로
          push: true # 빌드 후 푸시
          tags: | # 여러 태그 지정 가능
            ${{ secrets.DOCKERHUB_USERNAME }}/my-k8s-nginx-app:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/my-k8s-nginx-app:${{ github.sha }}
          # github.sha는 커밋 해시를 의미하며, 버저닝에 유용합니다.
          # DOCKERHUB_USERNAME 은 hansclub 으로 대체됩니다.
          # 예: hansclub/my-k8s-nginx-app:latest
          # 예: hansclub/my-k8s-nginx-app:ec1112497a3709b3e30fbc546cfd5aa59a58366a
